apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: localpv-provisioner
    repo: https://openebs.github.io/dynamic-localpv-provisioner
    version: 3.3.0
    releaseName: localpv-provisioner
    namespace: kube-system
    includeCRDs: true 
    valuesInline:
      openebsNDM:
        enabled: false
      deviceClass:
        enabled: false
      hostpathClass:
        enabled: true
        isDefaultClass: true
commonAnnotations:
  meta.helm.sh/release-name: localpv-provisioner
  meta.helm.sh/release-namespace: kube-system
commonLabels:
  app.kubernetes.io/managed-by: Helm
patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          pod-security.kubernetes.io/enforce: privileged
